# Generated by Django 3.2.18 on 2023-03-11 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0002_university_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='address',
            field=models.CharField(default='empty', max_length=500),
        ),
    ]
